# ニューラルネットワークの復習

## 数学とPython

Pythonを使ってベクトルや行列を生成してみる. 

In [2]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [7]:
W.ndim

2

行列の要素関を計算してみる. 

In [10]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + x

array([[2, 4, 6],
       [5, 7, 9]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### ブロードキャスト

numpyの多次元配列では、形状の異なる配列どうしの演算も可能である. 

In [12]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [13]:
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

### ベクトルの内積と行列積

転地操作などは特に起こってはいないようだ.


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b) 

32

In [16]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7,8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [18]:
# 行ベクトルを引数にしているのに, そのまま計算がでしまうのは
# 若干恐いのだが..
np.dot(A, a[:2])

array([ 5, 11])

numpyについては[100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)をやるのが一番よい. 

## ニューラルネットワークの推論

In [3]:
import numpy as np
W1 = np.random.randn(2, 4) # 重み
b1 = np.random.randn(4) #バイアス
x = np.random.randn(10, 2) # 入力
h = np.dot(x, W1) + b1

In [7]:
def sigmoid (x):
    return 1 / (1 + np.exp(-x))

In [9]:
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)
a = sigmoid(h)
s = np.dot(a, W2) + b2

In [10]:
a

array([[0.44917117, 0.99872365, 0.61989562, 0.97834934],
       [0.36657851, 0.95697017, 0.74822877, 0.89497243],
       [0.59540909, 0.95757735, 0.80895092, 0.69281392],
       [0.84417831, 0.86370153, 0.90049452, 0.1387022 ],
       [0.58505863, 0.61271726, 0.87790381, 0.32350186],
       [0.49862698, 0.68129517, 0.85537096, 0.48635132],
       [0.43122638, 0.89199907, 0.80154119, 0.76031544],
       [0.61556464, 0.97093631, 0.80138559, 0.71710026],
       [0.75394978, 0.42378589, 0.91886466, 0.08985318],
       [0.42833697, 0.88251263, 0.80391274, 0.75282892]])

In [13]:
sigmoid(h[0,0])

0.4491711688330162

> スコアとは「確率」になる前の値である。スコアの値が高ければ高いほど、そのニューロンに血会おうするクラスの確率も高くなる. 一般にはスコアをSoftmax関数に入れて確率値に変換する. 

### レイヤとしてのクラス化と順伝播の実装

本書では次の実装ルールのもとニューラルネットワークを実装したＰｙｔｈｏｎクラスを作成していく. なお, 実装自体はPythonファイルに行うとする. 

- すべてのレイヤは、メソッドとしてforward()とbackward()を持つ
- すべてのレイヤは、インスタンス変数としてparmsとgradsを持つ

`py/forward_net.py`を利用して, Affine, Sigmoido, Affineレイヤを経てスコアSを出力するニューラルネットワークを作成する. 

In [1]:
from pynet import forward_net

In [2]:
import numpy as np
x = np.random.randn(10, 2)
model = forward_net.TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [3]:
s

array([[-0.00376227,  0.85517399,  0.16611614],
       [-0.0862226 ,  0.98878212,  0.20656062],
       [-0.32080132,  1.22949549,  0.25314898],
       [-0.6421173 ,  1.0057909 , -0.06976051],
       [-0.35781459,  0.93511593,  0.03493629],
       [ 0.23169698,  0.33067772,  0.00243652],
       [ 0.60621753,  0.11973821,  0.45807412],
       [ 0.29788205,  0.47360629,  0.16196393],
       [ 0.63872655,  0.0241712 ,  0.42569685],
       [ 0.20487644,  0.79631997,  0.35448416]])