# ニューラルネットワークの復習

## 数学とPytho

Pythonを使ってベクトルや行列を生成してみる. 

In [2]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [7]:
W.ndim

2

行列の要素関を計算してみる. 

In [10]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
W + x

array([[2, 4, 6],
       [5, 7, 9]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### ブロードキャスト

numpyの多次元配列では、形状の異なる配列どうしの演算も可能である. 

In [12]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [13]:
b = np.array([10, 20])
A * b

array([[10, 40],
       [30, 80]])

### ベクトルの内積と行列積

転地操作などは特に起こってはいないようだ.


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b) 

32

In [16]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7,8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [18]:
# 行ベクトルを引数にしているのに, そのまま計算がでしまうのは
# 若干恐いのだが..
np.dot(A, a[:2])

array([ 5, 11])

numpyについては[100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)をやるのが一番よい. 